# Generated by Django 5.2 on 2025-05-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("username", models.CharField(max_length=122)),
                ("email", models.EmailField(max_length=254)),
                ("contact", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=225)),
                ("comment", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
